jxxghp/MoviePilot-Plugins

package.json, plugins/doubanrank/__init__.py
https://github.com/jxxghp/MoviePilot/issues/1197
本地测了下应该没啥问题
=> fix 豆瓣榜单识别问题

package.json, plugins/downloadsitetag/__init__.py
=> 新增 下载任务添加站点标签与一级分类 插件

package.json, plugins/removelink/__init__.py
新增插件【清理硬链接】，功能如下：
- 监测用户指定的目录，当监测到有文件被删除后将自动将监控目录下所有和它硬链接的文件删除
- 可以设置关键词，命中关键词的不做处理
- 支持消息推送。
=> 新增插件【清理硬链接】

package.json, plugins/downloadsitetag/__init__.py
[#1497](https://github.com/jxxghp/MoviePilot/issues/1497)
=> 分类自动创建/新增定时任务功能

package.json, plugins/removelink/__init__.py
【清理硬链接】插件升级到v1.1
修复一些bug：
https://github.com/jxxghp/MoviePilot-Plugins/issues/60#issue-2140906856
https://github.com/jxxghp/MoviePilot-Plugins/pull/53#issuecomment-1958957847
=> 更新插件【清理硬链接】

plugins/removelink/__init__.py
不好意思，之前没有测试下载及入库。
刚测试了下，会自动把下载好的内容删除，已修复
=> 修复【清理硬链接】v1.1引入的bug

package.json, plugins/diagparamadjust/__init__.py
新增【诊断参数调整】插件：
用于向emby发送请求利用Diagnostic设置替换参数，实现修正字幕偏移问题。
修正前
修正后
=> 新增【诊断参数调整】插件

plugins/qbcommand/__init__.py
=> fix: QB远程操作单独设置暂停周期或开始周期失效问题1677

plugins/trcommand/__init__.py
远程操作TR插件
1. 支持远程暂停种子
2. 支持远程开始种子
3. 支持Crontab 调度任务暂定、启用
4. 支持限速上传
5. 支持限速下载
以上功能在本地可被运行，并已完成自测，请求合并到主分支。
=> feature: TR远程操作插件

plugins/qbcommand/__init__.py
修复功能：
TR远程限速插件 关联 https://github.com/jxxghp/MoviePilot-Plugins/issues/104
验证：
代码在本地已被验证可以执行，自测完毕，请求合并主分支。
=> fix: 限速开关BUG 104

package.json, plugins/qbcommand/__init__.py
不好意思，忘记调整版本号，下次注意。
https://github.com/jxxghp/MoviePilot-Plugins/issues/104
=> feature: 升级QB远程控制插件版本号

package.json, plugins/qbcommand/__init__.py
修正仅在打开限速开关的情况下再发送限速相关的通知关联
https://github.com/jxxghp/MoviePilot-Plugins/issues/104
代码在本地可被执行，并验证功能正常，请求合并主分支。
=> fix: QB远程控制 104

package.json, plugins/trcommand/__init__.py
修复TR限速问题，同QB相同，关联
https://github.com/jxxghp/MoviePilot-Plugins/issues/104
代码在本地可被执行，功能验证正常，请求合并主分支。
=> fix: TR远程控制插件限速问题 104

package.json, plugins/crossseed/__init__.py
青蛙辅种助手增强兼容性
存量种子站点识别更准确，减少无用种子文件下载
被屏蔽种子增加校验，减少报错信息
=> 青蛙辅种助手增强兼容性

plugins/trackereditor/__init__.py
- 增加对tr4.x修改tracker支持；
测试环境：tr 4.0.3（对tr版本小于4.x代码无过多修改，未测试）
- 修复"修改tracker"计数问题；
fix https://github.com/jxxghp/MoviePilot/issues/1735
=> feat: 对tr4.x支持

package.json, plugins/trackereditor/__init__.py
=> fix 【tracker替换】版本号

package.json, plugins/crossseed/__init__.py
[修复状态绿点，passkey兼容冒号空格](https://github.com/jxxghp/MoviePilot-Plugins/commit/6c4a6cc0695e272f0b5a65730caef27790903655)
=> 修复状态绿点，passkey兼容冒号空格

plugins/crossseed/__init__.py
目前插件采用种子hash的方式定位种子文件，但在我这个qb4.6.3上，它是以种子标题来保存的，导致插件无法正确访问种子文件。
查阅了qb的源代码，似乎从4.4.0开始直到目前最新的4.6.4均是以标题加序号的方式来命名种子文件了，参考代码如下：
https://github.com/qbittorrent/qBittorrent/blob/release-4.4.0/src/base/bittorrent/session.cpp#L3947
https://github.com/qbittorrent/qBittorrent/blob/release-4.6.4/src/base/bittorrent/sessionimpl.cpp#L3125
我不太了解qb的api，暂时没找到获得种子文件正确路径的方法，只能通过调用导出种子接口，直接拿到二进制数据进行解析。
@lingjiameng
=> 青蛙辅种: 对于无法访问的qb种子，尝试导出后再进行解析

package.json, plugins/brushflow/__init__.py
调整日志记录，修复tranmission下载地址问题，请Review
=> fix brushflow tranmission

package.json, plugins/crossseed/__init__.py
=> 新增支持控制查询间隔时间

package.json, plugins/vcbanimemonitor/__init__.py
=> VCB插件版本号更新

package.json, plugins/removelink/__init__.py
=> Update removelink to v1.7 to remove empty folders

package.json, plugins/removelink/__init__.py
修复删除空目录时只删除最后一层子目录而不删除其上层目录的问题
=> Update RemoveLink version to 1.8

package.json, plugins/crossseed/__init__.py
Fix:更换憨憨接口为nexusapi/pieces-hash
=> Fix:青蛙辅种插件更换憨憨接口

package.json, plugins/neodbsync/__init__.py
=> fix neodbsync

plugins/sitestatistic/__init__.py
如果当天特定站点 更新失败 则使用前一天的数据
防止面板出现由于 缺少前一天数据 而出现的 大量上传
=> feat(sitestatistic): add remove_failed option 

package.json, plugins/crossseed/__init__.py
[青蛙辅种插件支持代理](https://github.com/jxxghp/MoviePilot-Plugins/commit/2af33394776deb48f130f8bdd5fdeb533fc9af73)
=> feat: 青蛙辅种插件支持代理

package.json, plugins/qbcommand/__init__.py
增加功能，可选某些站点不再做种（通过插件暂定后不会被插件恢复做种）
=> Update qbcommand to version 1.4

package.json, plugins/iyuuautoseed/__init__.py
=> 增加不辅种小体积种子功能

package.json, plugins/contractcheck/__init__.py, plugins/contractcheck/siteuserinfo/__init__.py
=> Update contractcheck to v1.2

package.json, plugins/qbcommand/__init__.py
=> Update qbcommand to v1.5

package.json, plugins/contractcheck/__init__.py, plugins/contractcheck/siteuserinfo/__init__.py
=> Update contractcheck to v1.3

plugins/sitestatistic/siteuserinfo/file_list.py
修复了FileList站点的做种数大于50时，做种数和做种体积统计错误的bug，优化了分享率的读取方法
=> 修复FileList做种数和做种体积错误的bug

package.json, plugins/contractcheck/__init__.py
=> Update contractcheck to v1.4

package.json, plugins/cleaninvalidseed/__init__.py
=> Update cleaninvalidseed to v1.1

package.json, plugins/cleaninvalidseed/__init__.py
=> Update cleaninvalidseed to v1.2

package.json, plugins/cleaninvalidseed/__init__.py
[清理QB无效做种]插件更新
1. 增加远程命令
2. 通过error_msg过滤，避免误删因tracker网络连接问题导致的未工作种子
=> Update cleaninvalidseed to v1.3

package.json, plugins/cleaninvalidseed/__init__.py
=> Update cleaninvalidseed to v1.4

package.json, plugins/cleaninvalidseed/__init__.py
【清理QB无效做种】更新
1. 增加通过分类、标签过滤不删除种子功能；
3. 全量通知提供更多信息
=> Update cleaninvalidseed to v1.5

package.json, plugins/torrenttransfer/__init__.py
[feat: 转移做种支持删除重复种子](https://github.com/jxxghp/MoviePilot-Plugins/commit/838ade49ac9cb889f8f56f290781f7e121b36cbf)
=> feat: 转移做种支持删除重复种子

package.json, plugins/iyuuautoseed/__init__.py
=> feat: qB 辅种支持跳过校验

package.json, plugins/iyuuautoseed/__init__.py
=> feat: 支持自定义辅种后标签、支持将站点名加入到辅种后标签

package.json, plugins/cleaninvalidseed/__init__.py
修复因消息内容包含'_'导致telegram API调用失败的问题
=> Update cleaninvalidseed to v1.7

package.json, plugins/cleaninvalidseed/__init__.py
=> Update cleaninvalidseed to v1.8

package.json, plugins/cleaninvalidseed/__init__.py
=> Update cleaninvalidseed to v1.9

package.json, plugins/cleaninvalidseed/__init__.py
=> Update cleaninvalidseed to v2.0

package.json, plugins/zvideohelper/DoubanHelper.py, plugins/zvideohelper/__init__.py
=> Update zvideohelper to v1.1

package.json
=> Update zvideohelper to v1.2

plugins/zvideohelper/__init__.py
=> Update __init__.py of zvideohelper v1.2

package.json, plugins/personmeta/__init__.py
演职人员刮削，人物图片调整为优先从TMDB获取，避免douban图片CDN加载过慢的问题
=> fix jxxghp/MoviePilot#2343

package.json, plugins/cleaninvalidseed/__init__.py
=> [feat] 清理QB无效做种插件 新增《仅标记》模式

package.json, plugins/speedlimiter/__init__.py
=> Update speedlimiter to v1.2

package.json, plugins/sitestatistic/__init__.py, plugins/sitestatistic/siteuserinfo/nexus_php.py, plugins/sitestatistic/siteuserinfo/yema.py
#403 修复YemaPT数据统计错误
修复PTT用户等级未统计
=> 站点数据统计插件问题修复

package.json, plugins/mediaservermsg/__init__.py
兼容处理Emby部分客户端暂停重复推送停止播放webhook的场景
=> fix 媒体库服务器通知v1.3\n兼容处理Emby部分客户端暂停重复推送停止播放webhook的场景

package.json, plugins/vcbanimemonitor/__init__.py, plugins/vcbanimemonitor/remeta.py
=> 更新：vcbanimemonitor 到 v1.8.2.2

package.v2.json, plugins.v2/brushflow/__init__.py
=> feat(BrushFlow): add support for v2 plugin

plugins.v2/sitestatistic/__init__.py
=> fix(SiteStatistic): replace refresh_userdata with self.refresh

package.json, package.v2.json, plugins.v2/autosignin/__init__.py, plugins.v2/autosignin/sites/52pt.py, plugins.v2/autosignin/sites/__init__.py, plugins.v2/autosignin/sites/btschool.py, plugins.v2/autosignin/sites/chdbits.py, plugins.v2/autosignin/sites/haidan.py, plugins.v2/autosignin/sites/hares.py, plugins.v2/autosignin/sites/hdarea.py, plugins.v2/autosignin/sites/hdchina.py, plugins.v2/autosignin/sites/hdcity.py, plugins.v2/autosignin/sites/hdsky.py, plugins.v2/autosignin/sites/hdupt.py, plugins.v2/autosignin/sites/mteam.py, plugins.v2/autosignin/sites/nexushd.py, plugins.v2/autosignin/sites/opencd.py, plugins.v2/autosignin/sites/pterclub.py, plugins.v2/autosignin/sites/pttime.py, plugins.v2/autosignin/sites/tjupt.py, plugins.v2/autosignin/sites/ttg.py, plugins.v2/autosignin/sites/u2.py, plugins.v2/autosignin/sites/yema.py, plugins.v2/autosignin/sites/zhuque.py, plugins.v2/brushflow/__init__.py
- MoviePilot V2 版本站点自动签到插件
- 考虑后续统一支持 `response` 编码预测的置信度，不在 v1 进行相关兼容，新增 v2 插件处理
=> feat(AutoSignIn): add support for v2 plugin

package.v2.json, plugins.v2/downloadsitetag/__init__.py
=> feat(DownloadSiteTag): add support for v2 plugin

package.v2.json, plugins.v2/mediaserverrefresh/__init__.py
=> feat(MediaServerRefresh): add support for v2 plugin

package.json, plugins/dynamicwechat/__init__.py, plugins/dynamicwechat/src/UpdateHelp.py, plugins/dynamicwechat/src/debug.py, plugins/dynamicwechat/update_help.py
配置两个第三方api主要缓解以下问题：
1. 需要经常在异地登陆使用企业微信的用户cookie经常失效，要异地电脑安装、配置cookieCC重新上传cookie的问题
2. 在仅有手机微信的情况下更新cookie相对麻烦
=> 在原来“自动设置动态IP到企业微信应用可信IP”的基础上添加了两个第三方应用的api

package.v2.json, plugins.v2/configcenter/__init__.py
=> feat(ConfigCenter): v3.1

package.v2.json, plugins.v2/configcenter/__init__.py
=> style:(ConfigCenter): v3.2

package.json, plugins/speedlimiter/__init__.py
- 修复多下载器时，限速比例分配错误问题
- 修复视频比特率大于带宽时，限速失效的问题
- 优化多下载器时的通知
- 新增预留带宽设置，应对突发流量和其他额外需求
=> 播放限速插件：修复bug；增加预留带宽设置；

package.v2.json, plugins.v2/mediaservermsg/__init__.py
=> feat(MediaServerMsg): add independent media server msg control

package.v2.json, plugins.v2/brushflow/__init__.py
=> feat(BrushFlow): v4.0

package.v2.json, plugins.v2/brushflow/__init__.py
=> fix(BrushFlow): v4.0.1

package.json, plugins/webhook/__init__.py
- 兼容 MoviePilot v2 版本事件调整
- fix jxxghp/MoviePilot#3523
=> fix(WebHook): v1.1

plugins.v2/iyuuautoseed/__init__.py, plugins.v2/qbcommand/__init__.py, plugins/crossseed/__init__.py, plugins/iyuuautoseed/__init__.py, plugins/qbcommand/__init__.py
=> fix: 为更多做种相关插件提供 qbittorrent 5 支持

package.json, plugins/pushplusmsg/__init__.py
之前代码里的plugin_version 和‎package.json 中的version不一致，这里也一并处理。
=> feat:增加群组编码,支持发送群组消息

package.v2.json, plugins.v2/brushflow/__init__.py
- 支持通过CRON表达式配置开启时间，固定10分钟为执行周期
=> feat(BrushFlow): v4.1

package.v2.json, plugins.v2/iyuuautoseed/__init__.py
默认为配置时走默认规则，配置主辅分离后辅种流程全部走辅种下载器
=> feat: IYUU自动辅种插件，增加主辅分离配置

package.v2.json, plugins.v2/brushflow/__init__.py
=> feat(BrushFlow): v4.3

package.v2.json, plugins.v2/brushflow/__init__.py
=> fix(BrushFlow): v4.3.1

package.v2.json, plugins.v2/sitestatistic/__init__.py
=> feat(SiteStatistic): v1.6

package.v2.json, plugins.v2/torrenttransfer/__init__.py
resolve #255
建议squash merge，commit有点乱
=> feat(torrenttransfer.v2): 支持跳过校验

package.json, plugins/invitessignin/__init__.py
=> 更新invites签到域名前缀

package.json, package.v2.json, plugins.v2/chatgpt/__init__.py, plugins.v2/chatgpt/openai.py, plugins/chatgpt/__init__.py, plugins/chatgpt/openai.py
兼容部分API提供商的路径不以/v1结尾
https://github.com/jxxghp/MoviePilot-Plugins/issues/686
=> Update: 更新ChatGPT插件,兼容/v1后仍有路径的API

package.v2.json, plugins.v2/subscribeclear/__init__.py
添加订阅清理插件，支持清理已下载的文件记录、QB种子，以及辅种
=> feat: add subscribe clear plugin

package.v2.json, plugins.v2/autosignin/__init__.py
=> fix 站点自动签到v2.6

package.v2.json, plugins.v2/doubansync/__init__.py
- 添加搜索下载配置项和相关信息提示，开启后优先搜索站点资源进行下载，下载失败或无资源时仍会添加订阅
- 更新插件版本号和作者信息
- 历史数据展示增加动作类型
新增配置项默认关闭，关闭情况下插件逻辑与之前完全一致。
=> feat(doubansync): 豆瓣想看插件新增搜索下载功能

plugins/ntfymsg/__init__.py
=> feat:ntfy添加Token认证和用户动作

package.json, plugins/autosubv2/__init__.py
=> autosubv2 v2.2 fix

package.json, plugins/cleaninvalidplugin/__init__.py
=> 新增 清理无效插件 功能

package.v2.json, plugins.v2/clashruleprovider/__init__.py, plugins.v2/clashruleprovider/clashruleparser.py, plugins.v2/clashruleprovider/dist/assets/__federation_expose_Page-DEA-0_Sq.css, plugins.v2/clashruleprovider/dist/assets/__federation_expose_Page-y2yjbals.js, plugins.v2/clashruleprovider/dist/assets/remoteEntry.js
=> fix(ClashRuleProvider): 修复分享链接解析错误

package.v2.json, plugins.v2/imdbsource/__init__.py, plugins.v2/imdbsource/imdbhelper.py
在正常模式下，插件通过`get_module`返回`recognize_media`方法实现媒体识别。否则， 插件会通过monkey patching `app.chain.ChainBase.recognize_media`返回结果以实现辅助识别。
=> update(ImdbSource) 支持通过 IMDb 源识别媒体

package.v2.json, plugins.v2/clashruleprovider/README.md, plugins.v2/clashruleprovider/__init__.py, plugins.v2/imdbsource/__init__.py, plugins.v2/imdbsource/imdbhelper.py, plugins.v2/tobypasstrackers/__init__.py
- ImdbSource: 支持异步执行
- ClashRuleProvider: 注册插件动作
- ToBypassTrackers: 修复插件动作
=> update ImdbSource, ClashRuleProvider and ToBypassTrackers

plugins.v2/torrenttransfer/__init__.py
修复issues
https://github.com/jxxghp/MoviePilot-Plugins/issues/870
=> fix:修复torrenttransfer错误的获取种子信息提示
