jxxghp/MoviePilot-Plugins

package.json, plugins/doubansync/__init__.py
测试结果
```
moviepilot  | INFO:    doubansync - 开始同步用户 xxx 的豆瓣想看数据 ...
moviepilot  | DEBUG:   connectionpool.py - Starting new HTTPS connection (1): www.douban.com:443
moviepilot  | DEBUG:   connectionpool.py - https://www.douban.com:443 "GET /feed/people/xxx/interests HTTP/1.1" 200 None
moviepilot  | INFO:    doubansync - 获取到用户 xxx 豆瓣RSS数据：10
moviepilot  | DEBUG:   chain - 请求模块执行：douban_info ...
moviepilot  | INFO:    douban - 开始获取豆瓣信息：25780594 ...
moviepilot  | DEBUG:   connectionpool.py - Starting new HTTPS connection (1): frodo.douban.com:443
moviepilot  | DEBUG:   connectionpool.py - https://frodo.douban.com:443 "GET /api/v2/movie/25780594?apiKey=0dad551ec0f84ed02907ff5c42e8ec70&os_rom=android&_ts=20231219&_sig=mZCKZXyOfaU%2BTP9XjAH4y4D8GZE%3D HTTP/1.1" 301 192
moviepilot  | DEBUG: …
```
=> 豆瓣想看-补全年份和类型信息，修复识别错误 https://github.com/jxxghp/MoviePilot/issues/1264

package.json, plugins/torrentremover/__init__.py
使用extend添加MP标签导致string被拆分为单个字母添加到tags中，导致无法正常使用。改为append。
=> Fix 自动删种任务错误

plugins/brushflow/__init__.py
经排查发现 #83 的问题在于我的 qb 没有做代理 ，qbittorrent 无法访问 https://u2.dmhy.org 这个域名，下载 torrent 的时候就失败了。
尝试过在 qb 中使用 proxy 来下载种子和 general 信息，但这种做法也有问题
1. 大部分梯子都屏蔽了 IPv6 ，因此部分 IPv6 only 的 tracker 会无法解析域名
2. 部分 tracker 屏蔽了机场的 ip 
3. 会有多个 IP 的问题（部分 PT 站比较严格，会需要额外报备）
出于以上考虑，我选择了在刷流插件中直接下载 torrent 的字节流并推送到 qb 这个方案。
可行性在于：
1. 在 mp 中并没有大量的流量会产生，且因为需要刮削，我选择给 mp 上代理，qb 保持直连，这种情况下 torrent 文件就可以下载下来，并且 qb（包括代码和依赖）中也预留了直接上传 torrent bytes 的 API
2. 一些 PT 会主动将 torrent 中的连接地址改为最新的没有被 GFW 墙的网址
在这个层面上，#83 表述的问题即可被解决。改进之后刷流插件添加一个 选项
开启后即可自动推送 bytes 到 qb
=> 支持MP离线下载种子后推送到QB

package.json, plugins/qbcommand/__init__.py
通过定时或者交互命令的方式操作QB，目前包含如下操作：
1. 支持定时任务和交互命令暂停QB所有种子
2. 支持定时任务和交互命令开始QB所有种子
3. 支持在插件中设置上传、下载限速，并有开关选择是否对上传、下载进行限速
4. 支持交互命令的方式切换上传、下载限速状态
=> 新增插件【QB远程操作】

package.json, plugins/downloadsitetag/__init__.py
原有插件逻辑中希望通过tracker的域名调用SitesHelper.get_indexer(domain)来匹配站点，但部分站点的tacker与站点域名并不一致，这里通过tracker_mappings来进行前置匹配，从而支持部分站点也能够被匹配到，请Review
=> 通过tracker补全站点时，部分站点tracker通过域名映射进行前置处理

plugins/crossseed/__init__.py
之前为了解决因开启QB的SQLite而导致找不到torrent文件的特例，我增加了种子导出功能作为备选应对。
但在低版本QB（<4.5.0）上会产生兼容问题（有反馈会导致mp重启）
为了兼容可能会增加额外的判断和界面开关，
这个我没精力去验证、优化老版QB，以及让TR下载器的行为一致，所以暂时取消导出功能
@lingjiameng
=> 青蛙辅种: 取消远程种子导出，避免不兼容低版本qb

package.json, plugins/brushflow/__init__.py
- 进一步优化订阅排除匹配逻辑，从媒体库缓存中读取订阅别名作为标题，提高排除命中率
- 鉴于部分用户对刷流操作和对应的风险没有充分认知，插件配置中相关的提示置顶显示
- 增加H&R做种时间配置项，当配置了H&R做种时间/分享率时，则H&R种子只有达到预期行为时，才会进行删除，如果没有配置H&R做种时间/分享率，则普通种子的删除规则也适用于H&R种子
- 刷流前置条件调整，原有逻辑为保种体积 > 实际做种体积，则允许继续刷流，调整为保种体积 > (实际做种体积 + 种子大小下限) 时，才允许继续刷流，进一步降低刷流频率，如果没有配置种子大小，则与原有逻辑保持一致
- 鉴于部分用户无法理解代理下载种子的逻辑，默认关闭代理下载种子，如日志中出现下载种子失败的情况，可检查下载器网络能否正常访问站点或对代理下载种子有充分认知后开启选项
=> fix brushflow

package.json, plugins/torrentremover/__init__.py
`sizes`是两个字符串，直接 *1024*1024*1024 会得到一个很长的字符串，再转换成 int 则会报错 
```
Exceeds the limit (4300 digits) for integer string conversion: value has 1073741824 digits; 
use sys.set_int_max_str_digits() to increase the limit
```
先转换成 float 解决这个问题，还可以支持小数，如 `0-0.5` 表示 0-0.5GB
=> fix jxxghp/MoviePilot#1756

package.json, plugins/crossseed/__init__.py
=> feat: 青蛙辅种插件跳过停用站点

package.json, plugins/removelink/__init__.py
由于用户提出新版本导致随机删除文件及偶现无法删除硬链接等问题，现将插件【清理硬链接】回退到v1.6。相关讨论见 #191 
新功能将继续在https://github.com/DzAvril/MoviePilot-Plugins仓库下演进，稳定后再合入主线。勇于尝鲜的用户可将该仓库添加到MP三方库配置中。
=> roll back removelink to v1.6

package.json, plugins/removelink/__init__.py
修复问题 #191 
原因是插件过滤QB临时文件.!qB，而下载完成后执行的动作是重命名，插件未监测重命名事件导致没有将新增文件添加到监控列表中，从而删除硬链接失败。
=> fix issue #191

plugins/sitestatistic/siteuserinfo/nexus_php.py
憨憨的下一页是 ">"  而不是 下一页。 所以目前只会统计第一页的做种体积和数量。
=> fix 只会统计憨憨种子信息第一页的bug

package.json, plugins/cleaninvalidseed/__init__.py
=> Update cleaninvalidseed to v1.6

package.json, plugins/brushflow/__init__.py, plugins/sitestatistic/__init__.py
- 站点刷流兼容选择站点为空的场景
- 站点数据统计支持刷新后触发插件事件，用于联动其他插件同步数据
=> feat: 支持刷新后触发插件事件

package.json, plugins/trendingshow/__init__.py
效果对比如下：
老大，现有的组件大小一开始是为手机还是pc设计的？想把大尺寸和小尺寸屏幕的组件大小分开设置。
=> 轮播图铺满全屏时，截取顶部部分

package.json, plugins/iyuuautoseed/__init__.py
#241
因缺少rsskey下载链接，无法转换。且原代码通用处理逻辑，无法正常适配莫妮卡的base_url。于是重写了一段方法用以适配。
经测试可用。暂未发现bug，或与其他站点冲突。
```
【INFO】2024-07-09 18:21:37,424 - iyuuautoseed - 成功添加辅种下载，站点：莫妮卡，种子链接：https://monikadesign.uk/torrents/download/205.xxxxxxxxx?https=1
【INFO】2024-07-09 18:21:37,409 - iyuuautoseed - 23bcb61xxxxxxxxxxxxxxx 跳过校验，请自行检查...
【INFO】2024-07-09 18:21:31,770 - iyuuautoseed - 添加下载任务：https://monikadesign.uk/torrents/download/205.xxxxxx?https=1 ...
【DEBUG】2024-07-09 18:21:31,749 - torrent.py - 解析种子：[MonikaDesign][76]Ef:.A.Fairy.Tale.of.the.Two.S02.1080p.BluRay.x265.FLAC.2.0-AI-Raws.torrent
```
=> fix #241 莫妮卡Url转换失败

package.json, plugins/autosignin/__init__.py, plugins/autosignin/sites/haidan.py
修复海胆签到页重定向丢失cookie，导致的检测签到失败，实际签到成功的问题
=> fix：修复海胆签到失败问题

package.json, plugins/syncdownloadfiles/__init__.py
`time.gmtime(timestamp)`获取的是UTC时间，转为字符串后为时区0的时间
后面代码中与DB中的last_sync_time字符串（带有时区）比较`if last_sync_time > str(torrent_date):`
导致上次同步后8h内，下载器新增的种子都无法满足条件
改为`time.localtime(timestamp)`获取当地时间进行比较
=> fix：修复时区问题导致的上次同步后8h内的种子不同步的问题

plugins/dirmonitor/__init__.py
修复有些大写后缀被排除的情况：
```
【DEBUG】2024-08-30 17:00:00,542 - dirmonitor - /mnt/MyPassport/downloads/电视剧/国外动漫/Mobile.Suit.Gundam.SEED.Destiny.01-50Fin.2004.BluRay.iPad.720p.AAC.x264/Mobile.Suit.Gundam.SEED.Destiny.2004.S01E42.BluRay.iPad.720p.AAC.x264.MP4 不是媒体文件
```
=> 将文件后缀名检查改为不区分大小写

package.v2.json, plugins.v2/brushflow/__init__.py
- 下载种子事件调整为 `PluginTriggered`，并支持事件信息中携带 `downloader`
=> fix(BrushFlow): trigger plugin event with downloader

package.json, plugins/dynamicwechat/__init__.py, plugins/dynamicwechat/update_help.py
1. 尝试使用‘设定’里的CookieCloud设置，可以使用自定义的CC
2. 无法使用的远程命令，但还是在函数结束时退出浏览器，防止日志报错
3. 关闭cookie输入框和修改插件配置界面文本
4. 使用内置的加密函数
5. 延长cookie任务成功时不输出日志
6. 调整验证码筛选条件
=> 简化输出日志，使用设置里的CC配置

package.json, plugins/dynamicwechat/__init__.py
当公网IP变动时，触发推送二维码。此时企业微信已经无法发送二维码图片，因此不再使用插件通知的方式发送二维码
=> 放弃self.post_message()的消息推送，还原成send_pushplus_message(),更新到1.1.4

plugins/iyuuautoseed/__init__.py
iyuu自动辅种
辅种结束后，一起开始所有辅种后暂停的种子（排除了出错的种子），即使人工确认也是手动开始这部分种子
=> 辅种结束后，一起开始所有辅种后暂停的种子（排除了出错的种子），即使人工确认也是手动开始这部分种子

package.json, package.v2.json, plugins.v2/iyuuautoseed/__init__.py, plugins/iyuuautoseed/__init__.py
qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
修改后
=> fix 6b0504d0

package.v2.json, plugins.v2/iyuuautoseed/__init__.py
不想使用主从分离，查询后报错：
【WARNING】2025-01-14 00:23:53,717 - iyuuautoseed - 尚未配置主辅分离下载器，请检查配置
【WARNING】2025-01-14 00:23:53,716 - iyuuautoseed - 尚未配置主辅分离下载器，请检查配置
添加的辅种任务不会自动开始，一直处于暂停状态
=> fix:未配置主辅分离时辅种未自动开始的问题

package.json, package.v2.json, plugins.v2/iyuuautoseed/__init__.py, plugins/iyuuautoseed/__init__.py
fix #513 #630
1. 没考虑到会直接把所有已暂停种子重新开始，即使不是辅出来的种子
2. 没考虑到会把 qB 跳检的种子自动开始，即使不直接报错，也需要人工确认
=> Revert 辅种结束后，一起开始所有辅种后暂停的种子（排除了出错的种子）

package.json, plugins/barkmsg/__init__.py
[Bark文档](https://bark.day.app/#/tutorial?id=%e8%af%b7%e6%b1%82%e5%8f%82%e6%95%b0)有说明使用device_keys进行批量推送，但实测官方服务器的api接口不支持，暂且先单独进行推送
=> 更新 BarkMsg 插件版本至 1.3-1，修复批量推送时 device_keys 使用问题

plugins.v2/chatgpt/__init__.py
红豆泥私密马赛, 把修改代码从另一个插件上复制过来时候没注意漏个括号, 又因为不是专职py开发, 编译器没装py语法校验, 出现了这种低级错误
=> fix: 修复ChatGPT插件中出现的错误格式

plugins.v2/doubansync/__init__.py
原始数据取自豆瓣想看中的dc:creator，适用与管理员添加多个豆瓣ID，不通ID订阅成功，发送…通知时区分豆瓣用户
=> 20250314 发送订阅通知时增加豆瓣昵称数据字段

plugins.v2/brushflow/__init__.py
#770 修正站点刷流插件更新后一直提示name 'should_delete' is not defined
=> 修正should_delete未被命名错误

plugins/workwechatmsg/__init__.py
已有版本发送消息时，日志输出：
【WARNING】2025-06-12 08:10:00,330 - log.py - 企业微信机器人消息发送失败，错误码：415，错误原因：
目前是调用 from app.utils.http import RequestUtils
默认值为：
```
if not content_type:
content_type = "application/x-www-form-urlencoded; charset=UTF-8"
```
根据官方文档，指定content-type为application/json
=> fix workwechatmsg content-type

plugins.v2/doubanrank/__init__.py
豆瓣榜单订阅目前的体验有些问题。
- MediaType.UNKNOWN被作为mtype参数一路透传，并在https://github.com/jxxghp/MoviePilot/blob/682f4fe608f362f4d9919a11816d04178c6f4fd5/app/chain/media.py#L238
处作为mtype获取tmdb信息，从而对于剧集失败。预期应该是None，从而在这一行不会使用参数传入的mtype，转而使用meta.type。测试用例rss：https://rsshub.email-once.com/douban/list/tv_chinese_best_weekly
- 同时与上一点相关的，在按照doubanid匹配到tmdb后，由于meta传参中meta.type是Media.UNKNONW，在recognize_media中会分别查询电影/剧集两个类型，会有较多错误信息出现：”tmdbapi.py - The resource you requested could not be found."。因此使用tmdbinfo中的media_type代替。测试用例rss：https://rsshub.email-once.com/douban/list/movie_weekly_best
- 对于豆瓣id，目前匹配要求在两个'/'之间，但存在情况豆瓣id处于末尾，这种case会无法匹配到豆瓣id，降低识别准确度。测试用例rss：https://rsshub.email-once.com/douban/list/tv_real_time_hotest
=> 【豆瓣榜单订阅】对于MediaType.UNKNOWN的处理；豆瓣id识别兼容最后斜杠缺失
